# Numpy Array Exercises

**Exercise 1**: 

Write a NumPy program to add a border (filled with `0`'s) around an existing array.

**Input**:
```python
[[ 1.  1.  1.]                                                          
 [ 1.  1.  1.]                                                          
 [ 1.  1.  1.]]
```

**Output**:
```python
[[ 0.  0.  0.  0.  0.]                                                  
 [ 0.  1.  1.  1.  0.]                                                  
 [ 0.  1.  1.  1.  0.]                                                  
 [ 0.  1.  1.  1.  0.]                                                  
 [ 0.  0.  0.  0.  0.]]
```

In [ ]:
# Exercise 1:
# [TODO]


**Exercise 2**: 

Write a NumPy program to find common values between two arrays.

**Input**:
```python
arr1 = np.array([0, 10, 20, 40, 60])
arr2 = np.arrar([10, 30, 40])
```

**Output**:
```python
np.array([10, 40])
```

In [ ]:
# Exercise 2:
# [TODO]


**Exercise 3**:

Write a NumPy program to find the union of two arrays. Union will return the unique, sorted array of values that are in either of the two input arrays.

**Input**:
```python
arr1 = np.array([0, 10, 20, 40, 60, 80])
arr2 = np.array([10, 30, 40, 50, 70])
```

**Output**:
```python
np.array([0, 10, 20, 30, 40, 50, 60, 70, 80])
```

In [3]:
# Exercise 3:
# [TODO]


**Exercise 4**: 

Write a NumPy program to create a 2-D array whose diagonal equals `[4, 5, 6, 8]` and `0`'s elsewhere.

**Output:**

```python
[[4 0 0 0]
[0 5 0 0]
[0 0 6 0]
[0 0 0 8]]
```

In [ ]:
# Exercise 4:
# [TODO]


**Exercise 5**: 

Write a NumPy program to test whether each element of a 1-D array is also present in a second array.

**Input:**
```python
arr1 = np.array([0, 10, 20, 30, 40, 50])
arr2 = np.array([0, 40, 70])
```

**Output:**

```python
[True, False, False, False, True, False, False]
```

In [ ]:
# Exercise 5:
# [TODO]
