# NumPy Introduction

![image](../../images/numpy_logo.png)

[**NumPy**](https://numpy.org/) is a Python package for large-scale data processing. It provides a high-performance multidimensional array object, called `ndarray`, and tools for working with these arrays.

**Arrays** are very frequently used in **Machine Learning** and **Data Science**. **Lists** in `Python` serve the role of arrays and are great to represent a single row of data, but they don't scale well. Thus, in order to work with large datasets, we need something much better.

The main reason why **NumPy** is so much faster than **lists** is because **NumPy** arrays are stored in memory in a contiguous block of memory, which makes them faster to access.

**Fun fact**: **NumPy** is partially written in `Python`, but most of the parts are implemented in `C`/`C++`.

# Install and Use NumPy for the first time

`numpy` should be automatically installed as part of `anaconda`. Nonetheless, if for some reasons it is missing, you can enter the following command in a `anaconda prompt` or a `terminal` to install `numpy`:

```bash
pip install numpy
```

You can verify that it is installed by entering the following codes in a cell in a notebook:

```python
try:
    import numpy as np
    print(f"The version of numpy is: {np.__version__}")
except ImportError:
    print("numpy is not installed!")
```

In [1]:
try:
    import numpy as np
    print(f"The version of numpy is: {np.__version__}")
except ImportError:
    print("numpy is not installed!")

The version of numpy is: 1.21.5


It is extremely common to use `np` as the alias for `numpy` in `Python`.

```python
import numpy as np
```

`as` is used to assign an alias to a module. The alias is used to refer to the module in the rest of the code.

First, let's go through an example to see the power of `numpy`. We'll start with 2 lists having `1,000,000` random numbers each.

```python
from random import randrange

list1 = [randrange(1,1000000) for i in range(1000000)]
list2 = [randrange(1,1000000) for i in range(1000000)]

print(f"list1 contains {len(list1):,} elements")
print(f"list2 contains {len(list2):,} elements")
```

In [9]:
from random import randrange

list1 = [randrange(1,1000000) for i in range(1000000)]
list2 = [randrange(1,1000000) for i in range(1000000)]

print(f"list1 contains {len(list1):,} elements")
print(f"list2 contains {len(list2):,} elements")

list1 contains 1,000,000 elements
list2 contains 1,000,000 elements


**Exercise**

1. Let's calculate the product of each pair of elements from the two lists `list1` and `list2`. In other words, given an index `i`, we want to calculate the product of `list1[i]` and `list2[i]`.
2. Save the list of products in a new list called `product_list`.

**Hint**: 
- Use `for` loop to iterate through the lists. 
- You can use `zip()` to iterate through the lists at the same time.
- List comprehension.

In [10]:
%%timeit
# [TODO]
# for loop ONLY approach
product_list = []
for i in range(len(list1)):
    product_list.append(list1[i] * list2[i])

141 ms ± 1.03 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [11]:
# show first 5 elements of product_list
product_list = []
for i in range(len(list1)):
    product_list.append(list1[i] * list2[i])
product_list[:5]

[219127982892, 466516376282, 230684349545, 882922940445, 35793135560]

In [12]:
%%timeit
# [TODO]
# list comprehension + zip approach
product_list = [a * b for a, b in zip(list1, list2)]

72.4 ms ± 244 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [13]:
# show first 5 elements of product_list
product_list = [a * b for a, b in zip(list1, list2)]
product_list[:5]

[219127982892, 466516376282, 230684349545, 882922940445, 35793135560]

`%%timeit` is a magic command that runs the code in the cell and measures the time it takes to run.

As you can see, we use `zip()` and **list comprehension** to work out an elegant way of calculating the pair-wise product of the two lists.
Nonetheless, we **won't be able to multiply the two lists together directly**. We'll need to use `numpy` to do that.

```python
list1 * list2 # will throw an error
```

In [14]:
list1 * list2

TypeError: can't multiply sequence by non-int of type 'list'

With `numpy`, we can easily multiply the 2 `numpy` arrays together. Let's import `numpy` and convert the 2 lists into `numpy.ndarray`.

```python
import numpy as np

np_list1 = np.array(list1)
np_list2 = np.array(list2)

print(type(np_list1), type(np_list2))
```

In [15]:
import numpy as np

np_list1 = np.array(list1)
np_list2 = np.array(list2)

print(type(np_list1), type(np_list2))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [16]:
%%timeit
np_product_list = np_list1 * np_list2

1.81 ms ± 35.6 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [17]:
# show first 5 elements of np_product_list
np_product_list = np_list1 * np_list2
np_product_list[:5]

array([219127982892, 466516376282, 230684349545, 882922940445,
        35793135560])

**Exercise**

Let's build a summary table that looks like the one below based on the speed test we did earlier.

![image](../../images/np_speedtest_table.png)

<font size="5">[TODO] 📖</font>

|Method|Time taken|
|:-:|:-:|
|`for` loop|`148 ms ± 2.61 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)`|
|list comprehension|`76.2 ms ± 1.72 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)`|
|`numpy`|`1.99 ms ± 62.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)`|

Based on our simple experiment, we can see that `numpy` is the fastest method. In addition, using `numpy` allows us to write more efficient code while dealing with data.

**Exercise**

Why do we need `list` when we already have `numpy`?

**Hint**: Can `numpy` array contains elements of different types?

<font size="5">[TODO] 📖</font>

While `list` can contain elements of different types, `numpy` array can't. 
If you try to create this `numpy` array, you'll see that `numpy` automatically converts the elements of the list to the same type.

```python
np_example = np.array([1, "python", True])
```

In [18]:
# [TODO]
np_example = np.array([1, "python", True])
print(np_example)
print(np_example.dtype)

['1' 'python' 'True']
<U21


`<U21` means `unicode string`. [More info available here](https://numpy.org/doc/stable/reference/arrays.dtypes.html)

`np_list1` and `np_list2` both contains only `int64` data type.

```python
np_list1.dtype, np_list2.dtype
```

In [19]:
np_list1.dtype, np_list2.dtype

(dtype('int64'), dtype('int64'))

# Dimensions in Arrays

[**Dimensions**](https://www.splashlearn.com/math-vocabulary/geometry/dimensions) in mathematics are the measure of the size or distance of an object or region or space in one direction. In simpler terms, it is the measurement of the length, width, and height of anything. 

We have probably all come across **Catersian** coordianate system. Below is an illustration of 2-D coordinate system.

![image](../../images/1920px-Cartesian-coordinate-system.svg.png)

Types of figures based on dimensions:
- A point is a 0-dimensional object.
- A line is a 1-dimensional object.
- A plane is a 2-dimensional object.
- A volume is a 3-dimensional object.

![image](../../images/Dimensions-2.webp)

Similarly, arrays can have multiple dimensions.

**0-D Arrays**, or scalars, are the simplest arrays. For example, `np.array(1)` is a 0-D array.

```python
zero_d_array = np.array(1)

print(zero_d_array)
```

In [ ]:
zero_d_array = np.array(1)

print(zero_d_array)
print(f"Shape of zero_d_array: {zero_d_array.shape}")

1
Shape of zero_d_array: ()


As shown in the above example, `shape` is an attribute of `np.ndarray` object that returns the shape of the array. The **shape of an array** is the number of elements in each dimension. This is a very important method that you'll be using a lot when analysing data.

**1-D Arrays**, or vectors, are 1-dimensional arrays. For example, `np_product_list`, that we saw above, is a 1-D array.

```python
print(f"Shape of np_product_list: {np_product_list.shape}")
```

In [20]:
print(f"Shape of np_product_list: {np_product_list.shape}")

Shape of np_product_list: (1000000,)


We can see that `np_product_list` has 1 dimension containing `1000000` elements.

Below is another example:

![image](../../images/nparray_creation.png)

In [46]:
one_d_array = np.array([1, 2])

print(one_d_array)
print(f"Shape of one_d_array: {one_d_array.shape}")

[1 2]
Shape of one_d_array: (2,)


**2-D Arrays**, or matrices, are 2-dimensional arrays. For example, `np.array([1, 2, 3], [4, 5, 6])` is a 2-D array.

```python
matrix = np.array([1, 2, 3], [4, 5, 6])

print(matrix)
print(f"Shape of matrix: {matrix.shape}")
print(f"Number of dimensions of matrix: {matrix.ndim}")
```

In [31]:
matrix = np.array([
    [1, 2, 3], 
    [4, 5, 6]
])

print(matrix)
print(f"Shape of matrix: {matrix.shape}")
print(f"Number of dimensions of matrix: {matrix.ndim}")

[[1 2 3]
 [4 5 6]]
Shape of matrix: (2, 3)
Number of dimensions of matrix: 2


`matrix.shape` returns a tuple showing that the first dimension has 2 elements while the second dimension has 3 elements.

`matrix.ndim` returns the number of dimensions of the array.

**3-D Arrays** are arrays having matrices as its elements. For example, `np.array([[1, 2, 3], [4, 5, 6]])` is a 3-D array.

```python
three_d_array = np.array([[1, 2, 3], [4, 5, 6]])

print(three_d_array)
print(f"Shape of three_d_array: {three_d_array.shape}")
print(f"Number of dimensions of three_d_array: {three_d_array.ndim}")
```

In [30]:
three_d_array = np.array([
    [
        [1, 2, 3], 
        [4, 5, 6]
    ]
])

print(three_d_array)
print(f"Shape of three_d_array: {three_d_array.shape}")
print(f"Number of dimensions of three_d_array: {three_d_array.ndim}")

[[[1 2 3]
  [4 5 6]]]
Shape of three_d_array: (1, 2, 3)
Number of dimensions of three_d_array: 3


**Exercise**

Without using `ndim` method, can you figure out the number of dimensions of the following arrays?

```python
a = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
b = np.array([[1]])
c = np.array([[[1], [2], [3]], [[4], [5], [6]]])
d = np.array([[[[1], [2], [3]], [[4], [5], [6]]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
```

In [41]:
# [TODO]
a = np.array(0)
b = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
c = np.array([[1]])
d = np.array([[[[1], [2], [3]], [[4], [5], [6]]]])

print(f"array `a` has {a.ndim} dimension(s)")
print(f"array `b` has {b.ndim} dimension(s)")
print(f"array `c` has {c.ndim} dimension(s)")
print(f"array `d` has {d.ndim} dimension(s)")

array `a` has 0 dimension(s)
array `b` has 3 dimension(s)
array `c` has 2 dimension(s)
array `d` has 4 dimension(s)


**Exercise**

Without using `ndim` method, write a function that returns the number of dimensions of the array.

**Hint**: Similar to **list**, length of a **tuple** can be accessed using `len()` function. 

In [35]:
# [TODO]
def get_dimension(array):
    return len(array.shape)

# Access elements in an Array

Similar to **list**, we can access elements in an array using indexing or slicing.

![image](../../images/nparray_slicing.png)

```python
arr = np.array([1, 2])

print(f"Element at index 0: {arr[0]}")
print(f"Elements from index 0 to 2 (not inclusive): {arr[0:2]}")
```

In [53]:
arr = np.array([1, 2])

print(f"Element at index 0: {arr[0]}")
print(f"Elements from index 0 to 2 (not inclusive): {arr[0:2]}")

Element at index 0: 1
Elements from index 0 to 2 (not inclusive): [1 2]


Similarly, by providing the indices of the element, we can easily access elements in a 2-D array.

![image](../../images/nparray_2d.png)

```python
two_d_array = np.array([[1, 2, 3], [4, 5, 6]])

print(f"Element at index (0, 2): {two_d_array[0, 2]}")
```

In [45]:
two_d_array = np.array([
    [1, 2, 3], 
    [4, 5, 6]
])

print(f"Element at index (0, 2): {two_d_array[0, 2]}")

Element at index (0, 2): 3


# Modify Arrays

Similar to **list**, we can also modify the arrays by assigning new values to the elements.

```python
two_d_array = np.array([[1, 2, 3], [4, 5, 6]])

print("Before: ")
print(two_d_array)

two_d_array[0, 2] = 10
print("----------------------")
print("After: ")
print(two_d_array)
```

In [8]:
two_d_array = np.array([[1, 2, 3], [4, 5, 6]])

print("Before: ")
print(two_d_array)

two_d_array[0, 2] = 10
print("----------------------")
print("After: ")
print(two_d_array)

Before: 
[[1 2 3]
 [4 5 6]]
----------------------
After: 
[[ 1  2 10]
 [ 4  5  6]]


# Sort Arrays

There are many times when we need to sort the elements of an array. Luckily, there is a method called `np.sort()` for that purpose.

```python
arr = np.array([3, 1, 2, 3, 4, 8, 1, 4, 7, 0])

print("Before: ")
print(arr)
print("----------------------")
print("After: ")
print(arr.sort())
```

In [10]:
arr = np.array([3, 1, 2, 3, 4, 8, 1, 4, 7, 0])

print("Before: ")
print(arr)
print("----------------------")
print("After: ")
print(np.sort(arr))

Before: 
[3 1 2 3 4 8 1 4 7 0]
----------------------
After: 
[0 1 1 2 3 3 4 4 7 8]


Can `np.sort()` be used for 2-D arrays?

```python
two_d_array = np.array([[2, 1, 7], [6, 5, 4]])

print("Before: ")
print(two_d_array)

print("----------------------")
print("After: ")
print(np.sort(two_d_array))
```

In [12]:
two_d_array = np.array([[2, 1, 7], [6, 5, 4]])

print("Before: ")
print(two_d_array)

print("----------------------")
print("After: ")
print(np.sort(two_d_array))

Before: 
[[2 1 7]
 [6 5 4]]
----------------------
After: 
[[1 2 7]
 [4 5 6]]


We can see that the `np.sort()` function sorts the array dimension by dimension in ascending order by default.

`np.sort()` function is actually a lot more than that. Nonetheless, we shouldn't worry about it here. You can read more about `np.sort()` [here](https://numpy.org/doc/stable/reference/generated/numpy.sort.html).

# Searching Arrays

It is also very common to search for elements in an array. We will learn how to do that using `np.where()` method.

**NOTE**: `np.where()` is a very common method for data professionals.

In the following example, let's say we have an array `heights` containing the heights (in cm) of applicants for a flight attendant position. As this is a job having a strict height requirement (≥ 1.70 cm), we need to find out which applicants are qualified based on their heights. We will be using `np.where()` to filter out the index within the `heights` array of the qualified applicants.

```python
heights = np.array([1.63, 1.68, 1.71, 1.89, 1.79, 1.56, 1.7])

print(np.where(heights >= 1.7))
```

In [86]:
heights = np.array([1.63, 1.68, 1.71, 1.89, 1.79, 1.56, 1.7])

print(np.where(heights >= 1.7))

(array([2, 3, 4, 6]),)


As you can see, `np.where()` returns all the indices of the elements that satisfy the condition.

**Exercise**

Let's find out the indices of the odd elements in the following array.

```python
numbers = np.array([10, 20, 11, 40, 1, 54, 3])
```

In [24]:
# [TODO]
numbers = np.array([10, 20, 11, 40, 1, 54, 3])

print(np.where(numbers % 2 == 1))

(array([2, 4, 6]),)


**Exercise**

What else can `np.where()` do? Can we print the **docstring** of `np.where()`? 

In [30]:
# [TODO]
help(np.where)

Help on function where in module numpy:

where(...)
    where(condition, [x, y])
    
    Return elements chosen from `x` or `y` depending on `condition`.
    
    .. note::
        When only `condition` is provided, this function is a shorthand for
        ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
        preferred, as it behaves correctly for subclasses. The rest of this
        documentation covers only the case where all three arguments are
        provided.
    
    Parameters
    ----------
    condition : array_like, bool
        Where True, yield `x`, otherwise yield `y`.
    x, y : array_like
        Values from which to choose. `x`, `y` and `condition` need to be
        broadcastable to some shape.
    
    Returns
    -------
    out : ndarray
        An array with elements from `x` where `condition` is True, and elements
        from `y` elsewhere.
    
    See Also
    --------
    choose
    nonzero : The function that is called when x and y

As you can see, `np.where()` takes a condition as an argument and can also return `x` or `y` depending on the condition.

Thus, going back to the example about flight attendant applications above, we can use `np.where()` to generate a new array containing the result of each applicant's application based on their height.

```python
np.where(heights >= 1.7, "Accepted", "Rejected")

# array(['Rejected', 'Rejected', 'Accepted', 'Accepted', 'Accepted', 'Rejected', 'Accepted'], dtype='<U8')
```

In [32]:
np.where(heights >= 1.7, "Accepted", "Rejected")

array(['Rejected', 'Rejected', 'Accepted', 'Accepted', 'Accepted',
       'Rejected', 'Accepted'], dtype='<U8')

You can read more about `np.where()` [here](https://numpy.org/doc/stable/reference/generated/numpy.where.html).

What if we don't just want the indices of the elements that satisfy the condition, but the actual elements themselves?

Filtering in an array is very simple. You can combine the result returned by `np.where()` with the original array to get the elements that satisfy the condition.

Let's say we want to return all heights (in cm) of the applicants that are qualified.

```python
heights[np.where(heights >= 1.7)]
```

In [88]:
heights[np.where(heights >= 1.7)]

array([1.71, 1.89, 1.79, 1.7 ])

There is an even simpler way to do the exact same thing. We can drop `np.where()` completely and write the condition inside the square brackets.

```python
heights[heights >= 1.7]
```

In [89]:
heights[heights >= 1.7]

array([1.71, 1.89, 1.79, 1.7 ])

**Exercise**

How many applicants are qualified for the flight attendant position?

In [90]:
# [TODO]
print(f"There are {len(heights[heights >= 1.7]):,} people who are qualified for the flight attendant position.")

There are 4 people who are qualified for the flight attendant position.


# Array Arithmetic

We'll use the following 2 arrays to demonstrate some of the basic arithmetic operations that we can perform on arrays.

```python
arr1 = np.array([1, 2, 3])
arr2 = np.array([0, 5, 6])
```

In [34]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([0, 5, 6])

**Array addition** is performed element-wise. We can also add two arrays together using `np.add()` function.

![image](../../images/nparray_addition.png)

```python
arr1 + arr2

np.add(arr1, arr2)
```

In [36]:
arr1 + arr2

array([1, 7, 9])

In [37]:
np.add(arr1, arr2)

array([1, 7, 9])

**Array subtraction** is performed element-wise. We can also subtract two arrays together using `np.subtract()` function.

![image](../../images/nparray_subtraction.png)

```python
arr1 - arr2

np.subtract(arr1, arr2)
```

In [54]:
arr1 - arr2

array([ 1, -3, -3])

In [55]:
np.subtract(arr1, arr2)

array([ 1, -3, -3])

**Exercise**

What will be the result if we multiply `arr1` and `arr2` together?

In [56]:
# [TODO]
arr1 * arr2

array([ 0, 10, 18])

In [57]:
# [TODO]
np.multiply(arr1, arr2)

array([ 0, 10, 18])

**Array multiplication** is also performed element-wise. We can also multiply two arrays together using `np.multiply()` function.

**Exercise**

What will be the result if we divide `arr1` by `arr2`?

In [59]:
# [TODO]
arr1 / arr2

/tmp/ipykernel_12463/1771818627.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr1 / arr2


array([inf, 0.4, 0.5])

In [58]:
# [TODO]
np.divide(arr1, arr2)

/tmp/ipykernel_12463/3865805035.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(arr1, arr2)


array([inf, 0.4, 0.5])

Unsurprisingly, **array division** is also performed element-wise, and we can use `np.divide()` function to perform the division.

# Other useful functions

There are a number of functions that we can use to aggregate the elements of an array. They are very commonly used in data science. 
- `np.sum()`
- `np.mean()`
- `np.min()`
- `np.max()`
- `np.median()`
- `np.std()`

All of these functions can be applied to arrays of different dimensions. In my experience, the most common use case is to aggregate the elements of a 1-D array.

In [73]:
arr = np.array([1, 2, 3, 4, 5])

print(f"Sum of all elements: {np.sum(arr)}")
print(f"Average of all elements: {np.mean(arr)}")
print(f"The smallest element: {np.min(arr)}")
print(f"The largest element: {np.max(arr)}")
print(f"The median of the array: {np.median(arr)}")
print(f"The standard deviation of the array: {np.std(arr)}")

Sum of all elements: 15
Average of all elements: 3.0
The smallest element: 1
The largest element: 5
The median of the array: 3.0
The standard deviation of the array: 1.4142135623730951


# Transposing and Reshaping Arrays

**Transposing** is a simple operation that rotates the elements of an array. In order to transpose a matrix, we can either use `.T` or `np.transpose()` function. It's very common to use `.T`.

![image](../../images/nparray_transpose.png)

Let's look at an example:

```python
arr = np.array([[1, 4], [2, 5], [3, 6]])

print("Before transposing:")
print(arr)
print(f"Original array has {arr.shape} shape.")
print("\n")
print("After transposing:")
print(arr.T)
print(f"Transposed array has {arr.T.shape} shape.")
```

In [79]:
arr = np.array([[1, 4], [2, 5], [3, 6]])

print("Before transposing:")
print(arr)
print(f"Original array has {arr.shape} shape.")
print("\n")
print("After transposing:")
print(arr.T)
print(f"Transposed array has {arr.T.shape} shape.")

Before transposing:
[[1 4]
 [2 5]
 [3 6]]
Original array has (3, 2) shape.


After transposing:
[[1 2 3]
 [4 5 6]]
Transposed array has (2, 3) shape.


**Reshaping** is a more complicated operation. We can use `.reshape()` or `np.reshape()` function to reshape an array.

Let's say we want to reshape a 1-D array into a 2-D array.

![image](../../images/nparray_reshape.png)

```python
arr = np.array([1, 2, 3, 4, 5, 6])

print("Before reshaping:")
print(arr)
print(f"Original array has {arr.shape} shape.")
print("\n")
print("After reshaping:")
print(arr.reshape(2, 3))
print(f"Reshaped (2, 3) array has {arr.reshape(2, 3).shape} shape.")
print("\n")
print(arr.reshape(3, 2))
print(f"Reshaped (3, 2) array has {arr.reshape(3, 2).shape} shape.")
```

In [85]:
arr = np.array([1, 2, 3, 4, 5, 6])

print("Before reshaping:")
print(arr)
print(f"Original array has {arr.shape} shape.")
print("\n")
print("After reshaping:")
print(arr.reshape(2, 3))
print(f"Reshaped (2, 3) array has {arr.reshape(2, 3).shape} shape.")
print("\n")
print(arr.reshape(3, 2))
print(f"Reshaped (3, 2) array has {arr.reshape(3, 2).shape} shape.")

Before reshaping:
[1 2 3 4 5 6]
Original array has (6,) shape.


After reshaping:
[[1 2 3]
 [4 5 6]]
Reshaped (2, 3) array has (2, 3) shape.


[[1 2]
 [3 4]
 [5 6]]
Reshaped (3, 2) array has (3, 2) shape.


# Broadcasting

**Broadcasting** describes how **NumPy** handles the case when two arrays have different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. 

Thus, with the help of broadcasting, we can perform arithmetic operations on array and scalar values since scalar values are considered 0-dimensional arrays.

![image](../../images/nparray_addition_scalar.png)

```python
arr1 + 1
```

In [53]:
arr1 + 1

array([2, 3, 4])

In this case, `1` is broadcasted into an array of shape `(3,)` having all element as the value of the scalar `1`.

Can the following operation be performed? Remember that: `arr1 = np.array([1, 2, 3])`

```python
arr1 + np.array([2, 3])
```

In [42]:
# [TODO]
arr1 + np.array([2, 3])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

Unfortunately, this is not possible. The two arrays are not **broadcastable**.

How do we determine if arrays are **broadcastable**?
- The arrays all have exactly the same shape.
- The arrays all have the same number of dimensions and the length of each dimensions is either a common length or 1.
- Arrays that have too few dimensions can have their shapes prepended with a dimension of length 1 to satisfy property 2.

It's **quite difficult to understand**, isn't it? 😂

I personally use `np.broadcast_to()` function to broadcast the array to the same shape as the other array. If it returns in an error, it means that the two arrays are not **broadcastable**. 

In [50]:
np.broadcast_to(np.array([2, 3]), arr1.shape)

ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (2,)  and requested shape (3,)

In [51]:
np.broadcast_to(1, arr1.shape)

array([1, 1, 1])